In [1]:
import sys
import os
import pandas as pd
current_path = os.getcwd()
parent_dir = os.path.join(current_path, "..")
print("Current working directory:", current_path)
print("Path to the parent directory:",parent_dir)
sys.path.append(parent_dir)
import simulator as sm
import numpy as np
import astropy.units as U
from casatasks import exportfits, simobserve, tclean, gaincal, applycal
from casatools import table
from casatools import simulator as casa_simulator
import random
import shutil
from astropy.constants import c
import math
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord
from scipy.optimize import curve_fit
import  utility.skymodels as sku
import utility.alma as au
import utility.astro as uas

Current working directory: /home/astro/Documents/GitHub/ALMASim/experimental
Path to the parent directory: /home/astro/Documents/GitHub/ALMASim/experimental/..


In [6]:
import h5py
file = os.path.join(parent_dir, 'metadata', 'morphologies_deeplearn.hdf5')
data = list()
column_names = list()
r = h5py.File(file, 'r')
for key in r.keys():
    print(key)

Header
Snapshot_95
Snapshot_99


In [3]:
snapshot = 61
tng_dir = '/mnt/storage/astro/TNGData'
outpath = os.path.join(tng_dir, 'TNG100-1', 'output', 'snapdir_0{}'.format(snapshot))
n_sims = 10
main_path = parent_dir
tng_subhaloids = uas.get_subhaloids_from_db(n_sims, main_path)
tng_api_key = '8f578b92e700fae3266931f4d785f82c'
for tng_subhaloid in tng_subhaloids:
    redshift = 1
    snapshot = uas.redshift_to_snapshot(redshift)
    
    part_num = uas.get_particles_num(tng_dir, outpath, snapshot, int(tng_subhaloid), tng_api_key)
    print("Number of particles in the subhalo:", part_num)

Looking for Subhalo 445185 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 445185
[2553 3865    0    0   41    0]
Particles are found in Snapshot 59 which is not present on disk
Done.
Checking File 59...
Loading File 60...
Number of particles in the subhalo: 2553
Looking for Subhalo 261959 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 261959
[ 0 91  0  0  0  0]
Number of particles in the subhalo: 0
Looking for Subhalo 369545 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 369545
[ 0 84  0  0  0  0]
Number of particles in the subhalo: 0
Looking for Subhalo 595586 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 595586
[  0 570   0   0   0   0]
Number of particles in the subhalo: 0
Looking for Subhalo 114459 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 114459
[  0 103   0   0   0   0]
Number of particles in the subhalo: 0
Looking for Subhalo 14 in snapshot 50
Checking offset in Snapshot 50 for grouphalo 14
[20726 33944     0